import { EventEmitter } from 'events';

export const eventBus = new EventEmitter();
eventBus.setMaxListeners(50);

export const EVENTS = {
  QUEUE_UPDATE: 'QUEUE_UPDATE',
  WAIT_PREDICTION: 'WAIT_PREDICTION',
  SHOCK_EVENT: 'SHOCK_EVENT',
  SHOCK_RESOLVED: 'SHOCK_RESOLVED',
  ALERT: 'ALERT',
  FAIRNESS_VIOLATION: 'FAIRNESS_VIOLATION',
  PRIORITY_ACCESS: 'PRIORITY_ACCESS',
  STAFF_OVERRIDE: 'STAFF_OVERRIDE',
  SUSTAINABILITY_UPDATE: 'SUSTAINABILITY_UPDATE',
  DETECTION_UPDATE: 'DETECTION_UPDATE',
  SYSTEM_STATUS: 'SYSTEM_STATUS',
  DAILY_SUMMARY: 'DAILY_SUMMARY',
  DEMAND_FORECAST: 'DEMAND_FORECAST',
  HEATMAP_DATA: 'HEATMAP_DATA',
  AUDIT_EVENT: 'AUDIT_EVENT',
  STAFF_STATE: 'STAFF_STATE',
  DETECTION_UPDATE: 'DETECTION_UPDATE',
};
